# ASCII-Font › http://patorjk.com/software/taag/#p=display&f=Slant&t=Phlow
#
#      _____ _ __          _____      __  __  _
#     / ___/(_) /____     / ___/___  / /_/ /_(_)___  ____ ______
#     \__ \/ / __/ _ \    \__ \/ _ \/ __/ __/ / __ \/ __ `/ ___/
#    ___/ / / /_/  __/   ___/ /  __/ /_/ /_/ / / / / /_/ (__  )
#   /____/_/\__/\___/   /____/\___/\__/\__/_/_/ /_/\__, /____/
#                                                 /____/
#
# Title of your website
title: "Crossfit Asphodel"


# The slogan describes your website and is used on homepage in <title> and other important places
slogan: "WOD in progress"


# The description is used on homepage and in the footer to quickly describe your website. Use a maximum of 150 characters for SEO-purposes.
description: "The description is used on homepage and in the footer to quickly describe your website. Use a maximum of 150 characters for SEO-purposes."

# The credits show up in the includes/_footer.html
# Created with <3 by JHO, with devotion to all the great Coaches who had shined light on those places beyond the last rep.
credits: '<br><p>Created with &hearts; by <a href="http://johnho.ca/">JHO</a> with <a href="http://jekyllrb.com/" target="_blank">Jekyll</a> based on <a href="http://phlow.github.io/feeling-responsive/">Feeling Responsive</a>.</p>'

# Main author of the website
# See > authors.yml
author: jho

# This URL is the main address for absolute links. Don't include a slash at the end.
#
url: 'https://ohjho.github.io/asphodel2018'
baseurl: ''

# This is for the editing function in _/includes/improve_content
# Leave it empty if your site is not on GitHub/GitHub Pages
improve_content: https://github.com/ohjho/asphodel2018/edit/gh-pages

# This is the email for the contact page
contact_email: 'jho.sfu@gmail.com'

# For Google Map
# if frontpage_map_link not given, we display the google map result of searching the address
address: '22 Praya Street, Kennedy Town, Hong Kong'
gmap_api_key: 'AIzaSyBt_v7udLInJ1bujWHgDvpNCXeABS_BDsw'
frontpage_map_link: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d922.9508843212973!2d114.13146232100102!3d22.28543075281428!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3404010cafabaf53%3A0xacf344de533af41a!2sReebok+CrossFit+Asphodel!5e0!3m2!1sen!2sus!4v1516245780161"

# This URL points directly to the images directory making
# things easier to link to images in posts and templates. It needs a slash at the end.
#
# Example: <img src="{{ site.urlimg }}{{ post.image.title }}" />
# Markdown-Example for posts ![Image Text]({{ site.urlimg }}image.jpg)
#
urlimg: 'https://ohjho.github.io/asphodel2018/images/'
#urlimg: 'images/'

# Style Scheme: see options in _sass/_01_settings_colors-{}.scss and _sass/_02_settings_typography-{}.scss
style: panerai

# Logo size is 100x40 pixels
logo: "logo_white_100.png"

# Logo shown in header when there's no header image. Size is 600x 80
headerlogo: "logo_white_x80.png"

# background image, will use solid color if not given
bgimg: 'https://ohjho.github.io/asphodel2018/images/bg-concrete.jpg'
  #'https://source.unsplash.com/AupdmQ4w_M4/1600x900'   # red brick wall

# Paginates all X entries
paginate: 7 #<- one week's worth of programming


# Pagination path › Important for blog page in /blog/ to work
paginate_path: "blog/page:num"

# excerpt_separator to show excerpt from post
excerpt_separator: <!--more-->


# Theme works best with Kramdown (using the table of contents function)
markdown: kramdown
permalink: /:categories/:title/
highlight: rouge
gems: [jekyll-paginate]
excerpt_separator: "<!--more-->"
include: ['.htaccess']
# Exclude these files from your production _site
exclude:
    - .sass-cache
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - INSTALL.md


# The language setting is used in /includes/header.html for html-settings
language: "en"


# Used › default.html front-matter and compress.html
# Options › http://jch.penibelst.de
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  profile: false
  ignore:
    envs: [development]


#
#       ____       ____            ____
#      / __ \___  / __/___ ___  __/ / /_
#     / / / / _ \/ /_/ __ `/ / / / / __/
#    / /_/ /  __/ __/ /_/ / /_/ / / /_
#   /_____/\___/_/  \__,_/\__,_/_/\__/
#
# Default Settings

defaults:
  -
    scope:
      path: "" 				# an empty string here means all files in the project
      type: "pages"
    values:
      show_meta: false 	# Hide metadata for all pages
      # sidebar:    		# Possible values › left, right › by default there will be no sidebar
      comments: false
      author: jho     # Default author for pages
  -
    scope:
      path: ""
      type: "posts"
    values:
      show_meta: true   # Show metadata for all posts
      # sidebar:        # Possible values › left, right › by default there will be no sidebar
      comments: false
      author: ash     # Default author for posts



#       _   __            _             __  _
#      / | / /___ __   __(_)___ _____ _/ /_(_)___  ____
#     /  |/ / __ `/ | / / / __ `/ __ `/ __/ / __ \/ __ \
#    / /|  / /_/ /| |/ / / /_/ / /_/ / /_/ / /_/ / / / /
#   /_/ |_/\__,_/ |___/_/\__, /\__,_/\__/_/\____/_/ /_/
#                       /____/
#
#  Open _data/navigation.yml to adjust the left and right topbar navigation
#



#     _____ __________
#    / ___// ____/ __ \
#    \__ \/ __/ / / / /
#   ___/ / /___/ /_/ /
#  /____/_____/\____/    Verify Website to Webmaster Tools

# google_author:             ""
# google_site_verification:  ""
# bing_webmastertools_id:    ""
# alexa_verify_id:           ""



#       ______            _
#      / ____/___ __   __(_)________  ____  _____
#     / /_  / __ `/ | / / / ___/ __ \/ __ \/ ___/
#    / __/ / /_/ /| |/ / / /__/ /_/ / / / (__  )
#   /_/    \__,_/ |___/_/\___/\____/_/ /_/____/   Favicon-Crap: Favicons, Chrome, Android & Apple Touch Buttons
#                                                 More information » https://mathiasbynens.be/notes/touch-icons

# favicon-32x32:                          "favicon-32x32.png"
# touch-icon-192x192:                     "touch-icon-192x192.png"
# apple-touch-icon-180x180-precomposed:   "apple-touch-icon-180x180-precomposed.png"
# apple-touch-icon-152x152-precomposed:   "apple-touch-icon-152x152-precomposed.png"
# apple-touch-icon-144x144-precomposed:   "apple-touch-icon-144x144-precomposed.png"
# apple-touch-icon-120x120-precomposed:   "apple-touch-icon-120x120-precomposed.png"
# apple-touch-icon-114x114-precomposed:   "apple-touch-icon-114x114-precomposed.png"
# apple-touch-icon-76x76-precomposed:     "apple-touch-icon-76x76-precomposed.png"
# apple-touch-icon-72x72-precomposed:     "apple-touch-icon-72x72-precomposed.png"
# apple-touch-icon-precomposed:           "apple-touch-icon-precomposed.png"
# msapplication_tileimage:                "msapplication_tileimage.png"               # Size 144x144
# msapplication_tilecolor:                "#fabb00"

# check out https://realfavicongenerator.net for improvement and validation

favicon-32x32:                          "favicons/favicon-32x32.png"
touch-icon-192x192:                     "favicons/android-chrome-192x192.png"
apple-touch-icon-180x180-precomposed:   "favicons/apple-touch-icon.png"
apple-touch-icon-152x152-precomposed:   "favicons/apple-touch-icon.png"
apple-touch-icon-144x144-precomposed:   "favicons/apple-touch-icon.png"
apple-touch-icon-120x120-precomposed:   "favicons/apple-touch-icon.png"
apple-touch-icon-114x114-precomposed:   "favicons/apple-touch-icon.png"
apple-touch-icon-76x76-precomposed:     "favicons/apple-touch-icon.png"
apple-touch-icon-72x72-precomposed:     "favicons/apple-touch-icon.png"
apple-touch-icon-precomposed:           "favicons/favicon-16x16.png"
msapplication_tileimage:                "favicons/mstile-150x150.png"               # Size 144x144
msapplication_tilecolor:                "#fabb00"


#       ______                __                __
#      / ____/___ _________  / /_  ____  ____  / /__
#     / /_  / __ `/ ___/ _ \/ __ \/ __ \/ __ \/ //_/
#    / __/ / /_/ / /__/  __/ /_/ / /_/ / /_/ / ,<
#   /_/    \__,_/\___/\___/_.___/\____/\____/_/|_|      Facebook-Optimization › http://j.mp/fb_optimize

# og_image:                         ""
# og_locale:                        "en_EN"
# og_type:                          "website"
# og_title:                         ""
# og_description:                   ""
# og_url:                           ""
# og_site_name:                     ""


#      _____            _       __   __  ___         ___
#     / ___/____  _____(_)___ _/ /  /  |/  /__  ____/ (_)___ _
#     \__ \/ __ \/ ___/ / __ `/ /  / /|_/ / _ \/ __  / / __ `/
#    ___/ / /_/ / /__/ / /_/ / /  / /  / /  __/ /_/ / / /_/ /
#   /____/\____/\___/_/\__,_/_/  /_/  /_/\___/\__,_/_/\__,_/
#
#  Open _data/socialmedia.yml to adjust the left and right topbar navigation
#


#        ____  _
#       / __ \(_)________ ___  _______
#      / / / / / ___/ __ `/ / / / ___/
#     / /_/ / (__  ) /_/ / /_/ (__  )
#    /_____/_/____/\__, /\__,_/____/
#                    /_/
#
# used in _includes/comments

# disqus_shortname:


#      _____
#     / ___/____ ___________
#     \__ \/ __ `/ ___/ ___/
#    ___/ / /_/ (__  |__  )     More › http://sass-lang.com/
#   /____/\__,_/____/____/      More › http://jekyllrb.com/docs/assets/#sassscss
#

sass:
    sass_dir: _sass
    style: :compressed


#       ___                __      __  _
#      /   |  ____  ____ _/ /_  __/ /_(_)_________
#     / /| | / __ \/ __ `/ / / / / __/ / ___/ ___/
#    / ___ |/ / / / /_/ / / /_/ / /_/ / /__(__  )
#   /_/  |_/_/ /_/\__,_/_/\__, /\__/_/\___/____/      https://www.google.com/analytics/
#                        /____/
#
# used in _includes/footer_scripts

# google_analytics_tracking_id:



#   _                 _     _
#  | |_ __ ___      _| | __| |_ ___
#  | __/ _` \ \ /\ / / |/ /| __/ _ \
#  | || (_| |\ V  V /|   < | || (_) |
#   \__\__,_| \_/\_/ |_|\_(_)__\___/     More › https://www.tawk.to/knowledgebase/
#
#  tawk.to is a free live chat app that lets you monitor and chat
#  with visitors on your website or from a free customizable page
#
#  To load the script add tawkto: true in front matter of each page
#
# used in _includes/footer_scripts

# tawkto_embed_uri:


#
#     ____  __            _
#    / __ \/ /_  ______ _(_)___  _____
#   / /_/ / / / / / __ `/ / __ \/ ___/
#  / ____/ / /_/ / /_/ / / / / (__  )
# /_/   /_/\__,_/\__, /_/_/ /_/____/
#               /____/
#
# Plugins live in _plugins
# WARNING: user generated plugins are not supported.
#           see the doc: https://help.github.com/articles/adding-jekyll-plugins-to-a-github-pages-site/
#           or this gh-pages issue: https://github.com/jekyll/jekyll/issues/325
#           list of supported gh-pages plugins are here: https://pages.github.com/versions/

#plugins_dir: "./_plugins"

#plugins:
#- font_awesome

#gems:
#- font_awesome
