- menu_name: "Services"

# - name: "Contact"
#   url: "/contact/"
#   title: "Contact"

- name: "RSS"
  url: "/feed.xml"
  title: "Subscribe to RSS Feed"

- name: "Atom"
  url: "/atom.xml"
  title: "Subscribe to Atom Feed"

- name: "sitemap.xml"
  url: "/sitemap.xml"
  title: "Sitemap for Google Webmaster Tools"

- name: "Old site"
  url: "http://legacy.crossfitasphodel.com"
  title: "link to the old CrossfitAsphodel.com"

# - name: "Log an issue"
#   url: "https://github.com/ohjho/asphodel2018/issues/new"
#   title: "Found a bug with the site? Report it!"
